# AUTO-GENERATED: DO NOT EDIT BY HAND
# Generated by src/dynamic_prompt/generator/prompt_structure_generator.py
# python src/dynamic_prompt/generator/prompt_structure_generator.py  \
#   --in specs/prompt_structure/prompt_structure.yaml \
#   --out src/hyper_reasoning/prompts/prompt_structure.py

from typing import Any, Tuple, Type


class Stages:
    """Auto-generated hierarchical stage tree."""
    __top_levels__: Tuple[Type[Any], ...]
    __fixed_top_order__: Tuple[Type[Any], ...]

    class Objective:
        """ Defines the mission of the investigation and the boundaries of success. Describes what must be achieved, not how to achieve it. """
        __stage_display__: str = 'Objective'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

    class GlobalRules:
        """ Declares top-level constraints and priority principles that supersede other instructions. Ensures the investigation remains within intended boundaries. """
        __stage_display__: str = 'Global Rules'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

    class OperatingPrinciples:
        """ Captures expected reasoning and behavior throughout the investigation, including tool supervision, scope discipline, and outcome orientation. """
        __stage_display__: str = 'Operating Principles'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

    class ToolReference:
        """ Serves as a catalog of available tools with their high-level purposes and inputs, enabling informed tool selection during planning and execution. """
        __stage_display__: str = 'Tool Reference'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_fixed__: bool
        __order_index__: int

    class Scoping:
        """ Records what is in and out of scope for the incident. Establishes the focus areas and limits for subsequent analysis. """
        __stage_display__: str = 'Scoping'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

    class Planning:
        """ Outlines the intended approach to meet the objective, including chosen methods and criteria for determining success or failure. """
        __stage_display__: str = 'Planning'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

    class AdaptiveExecution:
        """ Describes how and when to adjust the plan based on emerging findings, including whether to broaden or narrow the focus and when to revisit prior steps. """
        __stage_display__: str = 'Adaptive Execution'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

        class AdaptiveExecutionRule:
            """ States the governing rule for inserting, skipping, or repeating steps during execution. """
            __stage_display__: str = 'Adaptive Execution Rule'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class ToolScopeSpecification:
            """ Defines how to select between broad exploration and deep focus given current evidence. """
            __stage_display__: str = 'Tool Scope Specification'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class BeforeToolExecution:
            """ States the preparation expectations before invoking a tool, including clarity of objective, scope, and relevant prior context. """
            __stage_display__: str = 'Before Tool Execution'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class AfterToolExecution:
            """ States how results should be validated and how the plan should be adjusted in response to tool outputs. """
            __stage_display__: str = 'After Tool Execution'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class ToolReengagement:
            """ Defines when to re-engage specific investigators or tools for targeted analysis. """
            __stage_display__: str = 'Tool Reengagement'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class SpecialCases:
            """ Collects predefined exception-handling patterns for unusual conditions, with an emphasis on explicit justification. """
            __stage_display__: str = 'Special Cases'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

    class ReflectAndReport:
        """ Synthesizes findings into a coherent account, consolidating evidence, timelines, and causal relationships across sources. """
        __stage_display__: str = 'Reflect And Report'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

        class Finalization:
            """ Closes the investigation record by updating name, summary, and status, and ensuring unrelated items are removed. """
            __stage_display__: str = 'Finalization'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

    class Output:
        """ Groups the schema and conventions for the user-facing result. """
        __stage_display__: str = 'Output'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

        class OutputTemplate:
            """ Specifies the required sections and structure of the final summary. """
            __stage_display__: str = 'Output Template'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

        class OutputTemplateRules:
            """ Specifies formatting and structural conventions for the final summary. """
            __stage_display__: str = 'Output Template Rules'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

    class QualityGates:
        """ Represents the final quality verification concept to confirm completeness, coherence, and defensibility of the delivered output. """
        __stage_display__: str = 'Quality Gates'
        __stage_root__: Type['Stages']
        __stage_parent__: Type[Any]
        __children__: Tuple[Type[Any], ...]
        __order_index__: int

        class DefinitionOfDone:
            """ Conditions that must be met before the job can be considered done. """
            __stage_display__: str = 'Definition Of Done'
            __stage_root__: Type['Stages']
            __stage_parent__: Type[Any]
            __children__: Tuple[Type[Any], ...]

Stages.Objective.__stage_root__ = Stages
Stages.Objective.__stage_parent__ = Stages
Stages.Objective.__children__ = ()

Stages.GlobalRules.__stage_root__ = Stages
Stages.GlobalRules.__stage_parent__ = Stages
Stages.GlobalRules.__children__ = ()

Stages.OperatingPrinciples.__stage_root__ = Stages
Stages.OperatingPrinciples.__stage_parent__ = Stages
Stages.OperatingPrinciples.__children__ = ()

Stages.ToolReference.__stage_root__ = Stages
Stages.ToolReference.__stage_parent__ = Stages
Stages.ToolReference.__children__ = ()

Stages.Scoping.__stage_root__ = Stages
Stages.Scoping.__stage_parent__ = Stages
Stages.Scoping.__children__ = ()

Stages.Planning.__stage_root__ = Stages
Stages.Planning.__stage_parent__ = Stages
Stages.Planning.__children__ = ()

Stages.AdaptiveExecution.__stage_root__ = Stages
Stages.AdaptiveExecution.__stage_parent__ = Stages
Stages.AdaptiveExecution.__children__ = (Stages.AdaptiveExecution.AdaptiveExecutionRule, Stages.AdaptiveExecution.ToolScopeSpecification, Stages.AdaptiveExecution.BeforeToolExecution, Stages.AdaptiveExecution.AfterToolExecution, Stages.AdaptiveExecution.ToolReengagement, Stages.AdaptiveExecution.SpecialCases,)

Stages.AdaptiveExecution.AdaptiveExecutionRule.__stage_root__ = Stages
Stages.AdaptiveExecution.AdaptiveExecutionRule.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.AdaptiveExecutionRule.__children__ = ()

Stages.AdaptiveExecution.ToolScopeSpecification.__stage_root__ = Stages
Stages.AdaptiveExecution.ToolScopeSpecification.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.ToolScopeSpecification.__children__ = ()

Stages.AdaptiveExecution.BeforeToolExecution.__stage_root__ = Stages
Stages.AdaptiveExecution.BeforeToolExecution.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.BeforeToolExecution.__children__ = ()

Stages.AdaptiveExecution.AfterToolExecution.__stage_root__ = Stages
Stages.AdaptiveExecution.AfterToolExecution.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.AfterToolExecution.__children__ = ()

Stages.AdaptiveExecution.ToolReengagement.__stage_root__ = Stages
Stages.AdaptiveExecution.ToolReengagement.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.ToolReengagement.__children__ = ()

Stages.AdaptiveExecution.SpecialCases.__stage_root__ = Stages
Stages.AdaptiveExecution.SpecialCases.__stage_parent__ = Stages.AdaptiveExecution
Stages.AdaptiveExecution.SpecialCases.__children__ = ()

Stages.ReflectAndReport.__stage_root__ = Stages
Stages.ReflectAndReport.__stage_parent__ = Stages
Stages.ReflectAndReport.__children__ = (Stages.ReflectAndReport.Finalization,)

Stages.ReflectAndReport.Finalization.__stage_root__ = Stages
Stages.ReflectAndReport.Finalization.__stage_parent__ = Stages.ReflectAndReport
Stages.ReflectAndReport.Finalization.__children__ = ()

Stages.Output.__stage_root__ = Stages
Stages.Output.__stage_parent__ = Stages
Stages.Output.__children__ = (Stages.Output.OutputTemplate, Stages.Output.OutputTemplateRules,)

Stages.Output.OutputTemplate.__stage_root__ = Stages
Stages.Output.OutputTemplate.__stage_parent__ = Stages.Output
Stages.Output.OutputTemplate.__children__ = ()

Stages.Output.OutputTemplateRules.__stage_root__ = Stages
Stages.Output.OutputTemplateRules.__stage_parent__ = Stages.Output
Stages.Output.OutputTemplateRules.__children__ = ()

Stages.QualityGates.__stage_root__ = Stages
Stages.QualityGates.__stage_parent__ = Stages
Stages.QualityGates.__children__ = (Stages.QualityGates.DefinitionOfDone,)

Stages.QualityGates.DefinitionOfDone.__stage_root__ = Stages
Stages.QualityGates.DefinitionOfDone.__stage_parent__ = Stages.QualityGates
Stages.QualityGates.DefinitionOfDone.__children__ = ()

Stages.Objective.__order_index__ = 0

Stages.GlobalRules.__order_index__ = 1

Stages.OperatingPrinciples.__order_index__ = 2

Stages.ToolReference.__order_fixed__ = True
Stages.ToolReference.__order_index__ = 3

Stages.Scoping.__order_index__ = 4

Stages.Planning.__order_index__ = 5

Stages.AdaptiveExecution.__order_index__ = 6

Stages.ReflectAndReport.__order_index__ = 7

Stages.Output.__order_index__ = 8

Stages.QualityGates.__order_index__ = 9

Stages.__top_levels__ = (
    Stages.Objective,
    Stages.GlobalRules,
    Stages.OperatingPrinciples,
    Stages.ToolReference,
    Stages.Scoping,
    Stages.Planning,
    Stages.AdaptiveExecution,
    Stages.ReflectAndReport,
    Stages.Output,
    Stages.QualityGates,
)

Stages.__fixed_top_order__ = (
    Stages.Objective,
    Stages.GlobalRules,
    Stages.OperatingPrinciples,
    Stages.ToolReference,
    Stages.Scoping,
    Stages.Planning,
    Stages.AdaptiveExecution,
    Stages.ReflectAndReport,
    Stages.Output,
    Stages.QualityGates,
)
